
import React, { useEffect, useState } from "react";
import { Shield, AlertTriangle, CheckCircle, Clock, FileVideo, Cpu, BarChart } from "lucide-react";

export default function PDFReportPage() {
    const [analysisResult, setAnalysisResult] = useState(null);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        const urlParams = new URLSearchParams(window.location.search);
        const analysisId = urlParams.get('id');

        if (analysisId) {
            const data = sessionStorage.getItem(`analysisResult-${analysisId}`);
            if (data) {
                const parsedData = JSON.parse(data);
                setAnalysisResult(parsedData);
                document.title = `DFV_FR_${parsedData.id.replace('analysis_', '')}`;
            }
        }
        setLoading(false);
    }, []);

    useEffect(() => {
        if (analysisResult && !loading) {
            // Delay print to allow content and images to render fully
            const printTimeout = setTimeout(() => {
                window.print();
            }, 1000);
            return () => clearTimeout(printTimeout);
        }
    }, [analysisResult, loading]);

    if (loading) {
        return <div style={{ fontFamily: 'sans-serif', textAlign: 'center', padding: '50px' }}>Loading Forensic Report...</div>;
    }

    if (!analysisResult) {
        return (
            <div style={{ fontFamily: 'sans-serif', textAlign: 'center', padding: '50px' }}>
                <h2>Report Generation Failed</h2>
                <p>Analysis data not found. Please close this tab and generate the report again from the results page.</p>
            </div>
        );
    }

    const isFakeVideo = (analysisResult.fake_frames_count / analysisResult.total_frames) * 100 > 30;
    const fakeFramesPercent = (analysisResult.fake_frames_count / analysisResult.total_frames) * 100;
    const realFramesPercent = 100 - fakeFramesPercent;

    return (
        <div className="watermark-container" style={{ fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif', color: '#1f2937' }}>
            <style>
                {`
                    @media print {
                        body { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
                        @page { size: A4; margin: 15mm; }
                        .no-print { display: none; }
                    }
                    .watermark-container::before {
                        content: 'DeepFakeVigilant';
                        position: fixed;
                        top: 50%;
                        left: 50%;
                        transform: translate(-50%, -50%) rotate(-45deg);
                        font-size: 8rem;
                        font-weight: bold;
                        color: #000;
                        opacity: 0.04;
                        z-index: -1;
                        text-align: center;
                    }
                    .report-table { width: 100%; border-collapse: collapse; margin-top: 1rem; }
                    .report-table th, .report-table td { border: 1px solid #e5e7eb; padding: 0.75rem; text-align: left; font-size: 0.9rem; }
                    .report-table th { background-color: #f9fafb; font-weight: 600; color: #0D47A1; }
                    .fake-frame-details { page-break-inside: avoid; }
                    .header-icon { display: flex; align-items: center; justify-content: center; width: 48px; height: 48px; background-color: #0D47A1; border-radius: 8px; }
                `}
            </style>
            
            <div className="no-print" style={{ textAlign: 'center', padding: '20px', backgroundColor: '#f3f4f6' }}>
                <p>Your report is being generated. If the print dialog doesn't appear automatically, please use your browser's print function (Ctrl/Cmd + P).</p>
            </div>

            <header style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', borderBottom: '3px solid #1976D2', paddingBottom: '1rem', marginBottom: '2rem' }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '1rem' }}>
                    <div className="header-icon">
                        <Shield color="#fff" size={28} />
                    </div>
                    <div>
                        <h1 style={{ color: '#0D47A1', margin: 0, fontSize: '2rem' }}>Forensic Video Analysis Report</h1>
                        <p style={{ margin: 0, color: '#4b5563' }}>Generated by DeepFakeVigilant</p>
                    </div>
                </div>
                <div style={{ textAlign: 'right', fontSize: '0.8rem', color: '#4b5563' }}>
                    <div><strong>Report ID:</strong> {analysisResult.id}</div>
                    <div><strong>Date:</strong> {new Date().toLocaleString()}</div>
                </div>
            </header>

            <main>
                <section style={{ marginBottom: '2rem' }}>
                    <h2 style={{ fontSize: '1.25rem', fontWeight: '600', color: '#0D47A1', borderBottom: '1px solid #d1d5db', paddingBottom: '0.5rem', marginBottom: '1rem' }}>Executive Summary</h2>
                    <table className="report-table">
                        <tbody>
                            <tr><th style={{ width: '30%' }}>Video File</th><td>{analysisResult.video_filename}</td></tr>
                            <tr><th>Overall Result</th>
                                <td style={{ fontWeight: 'bold', color: isFakeVideo ? '#b91c1c' : '#15803d', backgroundColor: isFakeVideo ? '#fee2e2' : '#dcfce7' }}>
                                    <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                                        {isFakeVideo ? <AlertTriangle size={18} /> : <CheckCircle size={18} />}
                                        {isFakeVideo ? 'Manipulation Detected' : 'Authentic Content Verified'}
                                    </div>
                                </td>
                            </tr>
                            <tr><th>Confidence Score</th><td>{analysisResult.overall_fakeness_score}% Likelihood of Manipulation</td></tr>
                        </tbody>
                    </table>
                </section>

                <section style={{ marginBottom: '2rem' }}>
                    <h2 style={{ fontSize: '1.25rem', fontWeight: '600', color: '#0D47A1', borderBottom: '1px solid #d1d5db', paddingBottom: '0.5rem', marginBottom: '1rem' }}>Analysis Metrics</h2>
                    <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1rem' }}>
                        <div style={{ border: '1px solid #e5e7eb', borderRadius: '8px', padding: '1rem' }}>
                            <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem', marginBottom: '0.5rem' }}>
                                <FileVideo size={20} color="#4b5563" />
                                <h3 style={{ margin: 0, fontSize: '1rem', fontWeight: '600' }}>Frame Analysis</h3>
                            </div>
                            <div>Total Frames: {analysisResult.total_frames}</div>
                            <div style={{ color: '#b91c1c' }}>Fake Frames: {analysisResult.fake_frames_count} ({fakeFramesPercent.toFixed(1)}%)</div>
                            <div style={{ color: '#15803d' }}>Real Frames: {analysisResult.total_frames - analysisResult.fake_frames_count} ({realFramesPercent.toFixed(1)}%)</div>
                        </div>
                        <div style={{ border: '1px solid #e5e7eb', borderRadius: '8px', padding: '1rem' }}>
                            <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem', marginBottom: '0.5rem' }}>
                                <Clock size={20} color="#4b5563" />
                                <h3 style={{ margin: 0, fontSize: '1rem', fontWeight: '600' }}>Performance</h3>
                            </div>
                            <div>Video Duration: {analysisResult.video_duration?.toFixed(2) || 'N/A'}s</div>
                            <div>Processing Time: {analysisResult.processing_time}s</div>
                            <div>Analysis Frame Rate: {analysisResult.frame_rate} FPS</div>
                        </div>
                    </div>
                </section>

                {analysisResult.fake_frames_count > 0 && (
                    <section style={{ marginBottom: '2rem', pageBreakBefore: 'auto' }}>
                        <h2 style={{ fontSize: '1.25rem', fontWeight: '600', color: '#0D47A1', borderBottom: '1px solid #d1d5db', paddingBottom: '0.5rem', marginBottom: '1rem' }}>Detected Manipulations</h2>
                        <table className="report-table">
                            <thead><tr><th>Frame No.</th><th>Timestamp</th><th>Manipulation Type</th><th>Confidence</th><th>Affected Regions</th></tr></thead>
                            <tbody>
                                {analysisResult.analysis_results.filter(f => f.is_fake).map((frame, index) => (
                                    <tr key={index} style={{ backgroundColor: index % 2 === 0 ? '#f9fafb' : '#fff' }} className="fake-frame-details">
                                        <td>{frame.frame_number}</td>
                                        <td>{frame.timestamp}s</td>
                                        <td>{frame.manipulation_type}</td>
                                        <td>{frame.confidence_score}%</td>
                                        <td>{frame.manipulated_regions?.join(', ') || 'N/A'}</td>
                                    </tr>
                                ))}
                            </tbody>
                        </table>
                    </section>
                )}

                <section style={{ pageBreakBefore: 'auto' }}>
                    <h2 style={{ fontSize: '1.25rem', fontWeight: '600', color: '#0D47A1', borderBottom: '1px solid #d1d5db', paddingBottom: '0.5rem', marginBottom: '1rem' }}>Technology & Methodology</h2>
                    <table className="report-table">
                        <tbody>
                            <tr><th style={{ width: '30%' }}>Detection Method</th><td>CNN-ELA-GAN Fusion with Semantic Consistency Check</td></tr>
                            <tr><th>Stated Accuracy</th><td>99.2% (in controlled environments)</td></tr>
                            <tr><th>Model Versions</th>
                                <td>
                                    CNN: {analysisResult.model_versions.cnn_model}, ELA: {analysisResult.model_versions.ela_model}, GAN: {analysisResult.model_versions.gan_model}, Semantic: {analysisResult.model_versions.semantic_model}
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </section>
            </main>

            <footer style={{ textAlign: 'center', marginTop: '3rem', paddingTop: '1rem', borderTop: '1px solid #d1d5db', fontSize: '0.75rem', color: '#6b7280' }}>
                <p><strong>Disclaimer:</strong> This report was generated by an automated AI system. Results are for informational purposes and should be considered alongside other verification methods. DeepFakeVigilant is not liable for any actions taken based on this report.</p>
                <p>© {new Date().getFullYear()} NetzSpaz / DeepFakeVigilant | https://deepfakevigilant.base44.app</p>
            </footer>
        </div>
    );
}
